[package]
name = "bib2"
version = "0.1.2"
edition = "2021"

[lib]
name = "bib2"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.0", features = ["extension-module", "abi3", "abi3-py38"]}
biblatex = { version = "0.10" }
