name: Build

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe: bib2json
          - os: windows-latest
            exe: bib2json.exe
          - os: macos-latest
            exe: bib2json

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build -r
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.exe }}
          path: target/release/${{ matrix.exe }}
